<?php

// Exit if accessed directly
if (!defined('ABSPATH')) {
	exit;
}

/**
 * Plugin default settings array - organized by section
 */
const FRL_DEFAULT_FIELDS = array(
	'website' => array(
		'title' => 'Website Settings',
		'fields' => array(
			'section_title_performance' => array(
				'label' => 'Performance',
				'description' => 'Performance settings',
				'type' => 'section_title',
			),
			'critical_css' => array(
				'label' => 'Preload critical CSS',
				'description' => 'Preload critical CSS from "critical.css" file in current theme directory',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'preload_featured' => array(
				'label' => 'Preload featured images',
				'description' => 'Preload featured images. Compatible with .webp format if available',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'defer_css' => array(
				'label' => 'Defer CSS Styles',
				'description' => 'Defer non-critical CSS Styles',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'defer_css_handles' => array(
				'label' => 'Deferred CSS String Matches',
				'description' => 'One handle per line, also plugin names can be used. The string is matched partially against the full URL of the style.',
				'type' => 'textlist',
				'default' => '
					blocks/cover/style
        			blocks/social-links/style
					columnedmegamenu.css
					ws-form
				',
				'sanitize_callback' => 'sanitize_textarea_field',
			),
			'remove_jqery_mig' => array(
				'label' => 'Remove jQuery Migrate',
				'description' => 'Remove jQuery Migrate compatibility script',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'disable_rest' => array(
				'label' => 'Disable REST',
				'description' => 'Disable REST API for selected endpoints',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'disable_oembed' => array(
				'label' => 'Disable oEmbeds',
				'description' => 'Disable oEmbeds support',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'disable_emojis' => array(
				'label' => 'Disable Emojis',
				'description' => 'Disable emojis sitewide',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'section_title_media' => array(
				'label' => 'Media Settings',
				'description' => 'Media tools for admin',
				'type' => 'section_title',
			),
			'svg_support' => array(
				'label' => 'SVG Media Support',
				'description' => 'Enable SVG media support',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'webp_support' => array(
				'label' => 'WEBP Media Support',
				'description' => 'Enable WEBP image support',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'sanitize_filename' => array(
				'label' => 'Sanitize Filenames',
				'description' => 'Sanitize filename and title of uploaded images to readable format.',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'image_sizes' => array(
				'label' => 'Add Media Image Sizes',
				'description' => 'Add custom image sizes to media library',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'image_sizes_list' => array(
				'label' => 'image Sizes List',
				'description' => 'One image size per line. Format: name|width|height|Label',
				'type' => 'textlist',
				'rows' => 3,
				'default' => '',
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'section_title_langswitcher' => array(
				'label' => 'Language Switcher',
				'description' => 'Polylang language switcher settings',
				'type' => 'section_title',
			),
			'langswitcher_dropdown' => array(
				'label' => 'Langswitcher Dropdown',
				'description' => 'Replace langswitcher flags with dropdown',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
			),
			'langswitcher_hide_current' => array(
				'label' => 'Hide Current Language',
				'description' => 'Hide current language link',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
			),
			'langswitcher_hide_if_no_translation' => array(
				'label' => 'Hide if No Translation',
				'description' => 'Hide language link if no translation',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
			),
			'langswitcher_hide_languages' => array(
				'label' => 'Hide Languages',
				'description' => 'One language slug per line.',
				'type' => 'textlist',
				'default' => '',
				'sanitize_callback' => 'sanitize_textarea_field',
			),
			'section_title_wordpress' => array(
				'label' => 'WordPress Features',
				'description' => 'Wordpress core features settings',
				'type' => 'section_title',
			),
			'disable_comments' => array(
				'label' => 'Disable Comments',
				'description' => 'Disable comments sitewide',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'login_branding' => array(
				'label' => 'Login Page Branding',
				'description' => 'Apply theme colors and logo to login page',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'custom_avatar' => array(
				'label' => 'Custom User Avatar',
				'description' => 'Upload a custom avatar for all users',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'editor_metabox' => array(
				'label' => 'Editor Metabox',
				'description' => 'Enable editor metabox in post edit screen',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'custom_wp_query' => array(
				'label' => 'Custom WP Query',
				'description' => 'Optimize secondary queries and order post types by ascending menu_order. One post type per line.',
				'type' => 'textlist',
				'default' => '
					service
					flag
					jurisdiction
				',
				'sanitize_callback' => 'sanitize_textarea_field',
			),
			'section_title_header' => array(
				'label' => 'Header Scripts & HTML',
				'description' => 'Add custom HTML and scriptsto the header',
				'type' => 'section_title',
			),
			'header_scripts' => array(
				'label' => 'Header Scripts',
				'description' => 'Absolute path to scripts to include. One per line.',
				'type' => 'textlist',
				'default' => '',
				'sanitize_callback' => 'sanitize_textarea_field',
				'restricted' => true,
			),
			'header_html' => array(
				'label' => 'Header HTML',
				'type' => 'html',
				'default' => '',
				'restricted' => true,
			),
			'header_html_php' => array(
				'label' => 'Allow PHP in header',
				'description' => 'Allow PHP code in the header HTML',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
				'restricted' => true,
			),
			'section_title_footer' => array(
				'label' => 'Footer HTML & Scripts',
				'description' => 'Add custom HTML and scripts to the footer',
				'type' => 'section_title',
			),
			'footer_scripts' => array(
				'label' => 'Footer Scripts',
				'description' => 'Absolute path to scripts to include. One per line.',
				'type' => 'textlist',
				'default' => '',
				'sanitize_callback' => 'sanitize_textarea_field',
				'restricted' => true,
			),
			'footer_html' => array(
				'label' => 'Footer HTML',
				'type' => 'html',
				'default' => '',
				'restricted' => true,
			),
			'footer_html_php' => array(
				'label' => 'Allow PHP in footer',
				'description' => 'Allow PHP code in the footer HTML',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
				'restricted' => true,
			),
			'section_title_schema' => array(
				'label' => 'Schema',
				'description' => 'Add schema to website pages',
				'type' => 'section_title',
			),
			'schema_article' => array(
				'label' => 'Article Schema',
				'description' => 'Add article schema to posts',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'schema_organization' => array(
				'label' => 'Organization Schema',
				'description' => 'Add organization schema sitewide',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'schema_service' => array(
				'label' => 'Service Schema',
				'description' => 'Add service schema to services',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'schema_portfolio' => array(
				'label' => 'Portfolio Schema',
				'description' => 'Add portfolio schema to portfolios',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
			),
			'schema_person' => array(
				'label' => 'Person Schema',
				'description' => 'Add person schema sitewide',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
			),
			'section_title_schema_owner_details' => array(
				'label' => 'Owner details',
				'description' => 'Add details for Person Schema  JSON-LD',
				'type' => 'section_title',
			),
			'schema_owner_name' => array(
				'label' => 'Owner name',
				'description' => 'Add owner name for Person/Portfolio Schema',
				'type' => 'text',
				'default' => 'Francesco Castronovo',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'schema_owner_description' => array(
				'label' => 'Owner description',
				'description' => 'Add owner description for Person Schema',
				'type' => 'text',
				'default' => 'Web Consultant',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'schema_owner_role' => array(
				'label' => 'Owner Role',
				'description' => 'Add owner role for Person Schema',
				'type' => 'text',
				'default' => 'Web Consultant',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'schema_owner_url' => array(
				'label' => 'Owner URL',
				'description' => 'Add owner URL for Person Schema',
				'type' => 'text',
				'default' => 'https://fralenuvole.art',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'schema_owner_image' => array(
				'label' => 'Owner image',
				'description' => 'Add owner image for Person Schema',
				'type' => 'text',
				'size' => 65,
				'default' => 'https://fralenuvole.art/wp-content/uploads/2025/02/francesco-castronovo-768x768.jpg',
				'sanitize_callback' => 'esc_url_raw',
				'autoload' => 'no',
			),
			'schema_owner_sameas' => array(
				'label' => 'Owner sameas',
				'description' => 'Add owner sameas for Person Schema',
				'type' => 'text',
				'default' => 'https://fralenuvole.art',
				'sanitize_callback' => 'esc_url_raw',
				'autoload' => 'no',
			),
		),
	),
	'administration' => array(
		'title' => 'Admin Tools',
		'fields' => array(
			'section_title_administration_general' => array(
				'label' => 'General',
				'description' => 'General administration settings',
				'type' => 'section_title',
			),
			'admin_theme_custom' => array(
				'label' => 'Custom Admin Theme',
				'description' => 'Enable custom admin theme in backend',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'logged_user_visits' => array(
				'label' => 'Log User Visits',
				'description' => 'Trace logged user visits',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'admin_featured_post_list' => array(
				'label' => 'Featured Image in Posts List',
				'description' => 'Show featured image in posts list',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'extend_admin_cookie' => array(
				'label' => 'Extend Admin Cookie',
				'description' => 'Extend admin cookie lifetime',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'section_title_adminbar' => array(
				'label' => 'Adminbar',
				'description' => 'Customise top adminbar menu',
				'type' => 'section_title',
			),
			'ab_remove_links' => array(
				'label' => 'Remove links in Adminbar',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'ab_remove_links_handles' => array(
				'label' => 'Links to remove for everybody',
				'description' => 'One link handle per line.',
				'type' => 'textlist',
				'default' => '
					comments
					customize
					new-user
					fdp-admin-top-bar
					ws-form-node
				',
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'ab_remove_links_handles_user' => array(
				'label' => 'Adminbar links to remove except for plugin admins',
				'description' => 'One link handle per line.',
				'type' => 'textlist',
				'default' => '
					query-monitor
					kwlm-menu
				',
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'custom_ab_menu' => array(
				'label' => 'Custom menu in Adminbar',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'custom_ab_links' => array(
				'label' => 'Custom Adminbar links',
				'description' => 'One link per line. Format: Label|URL',
				'type' => 'textlist',
				'default' => '',
				'cols' => 70,
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'section_title_admin_menu' => array(
				'label' => 'Admin menu',
				'description' => 'Customise left admin menu items',
				'type' => 'section_title',
			),
			'am_remove_links' => array(
				'label' => 'Remove links in Admin menu',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'am_remove_links_handles' => array(
				'label' => 'Admin links to remove for everybody',
				'description' => 'One link per line. Format: "menu_handle" for menus. "menu_handle|submenu_handle" for submenus. You can use also a string with part of the URL or the CSS class.',
				'type' => 'textlist',
				'default' => '',
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'am_remove_links_handles_user' => array(
				'label' => 'Admin links to remove except for plugin admins',
				'description' => 'One link per line. Format: "menu_handle" for menus. "menu_handle|submenu_handle" for submenus. You can use also a string with part of the URL or the CSS class.',
				'type' => 'textlist',
				'default' => '
					themes.php
					themes.php|site-editor.php
					themes.php|greenshifttheme_settings
					themes.php|site-editor.php?path=/patterns
				',
				'cols' => 70,
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'am_menu_limit' => array(
				'label' => 'Max number of admin menu items',
				'description' => 'Counts also separators. Leave 0 to show all items.',
				'type' => 'number',
				'default' => 0,
				'autoload' => 'no',
			),
			'am_menu_order' => array(
				'label' => 'Reorder Admin menu items',
				'description' => 'One menu / order number pair per line. Format: "menu_handle|number".',
				'type' => 'textlist',
				'default' => '',
				'rows' => 10,
				'cols' => 70,
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'am_menu_order_info' => array(
				'label' => 'Available Menu Items',
				'type' => 'custom',
				'callback' => 'frl_render_admin_menu_order',
			),
			'section_title_dashboard_widgets' => array(
				'label' => 'Dashboard Widgets',
				'description' => 'Customise Dashboard widgets',
				'type' 	=> 'section_title',
			),
			'dash_widget_last_posts' => array(
				'label' => 'Last modified posts widget',
				'description' => 'Show last modified posts in dashboard',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'dash_widget_editor' => array(
				'label' => 'Editor dashboard widget',
				'description' => 'Show editor dashboard widget',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'dash_widget_administrator' => array(
				'label' => 'Admin dashboard widget',
				'description' => 'Show admin dashboard widget',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'dash_widget_user_visits' => array(
				'label' => 'Logged users Widget',
				'description' => 'Show recent user activity on the dashboard',
				'type' => 'checkbox',
				'default' => '1',
				'autoload' => 'no',
			),
			'remove_dash_widg' => array(
				'label' => 'Remove dashboard widgets',
				'description' => 'Remove core and plugin dashboard widgets',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			'remove_dash_widg_handles' => array(
				'label' => 'Handles of widgets to remove',
				'description' => 'One widget handle per line.',
				'type' => 'textlist',
				'default' => '
					fluentsmtp_reports_widget
					kwlm-widget
					blc_dashboard_widget
				',
				'sanitize_callback' => 'sanitize_textarea_field',
				'autoload' => 'no',
			),
			'section_title_custom_html_widgets' => array(
				'label' => 'Custom HTML Widgets',
				'description' => 'Add custom HTML widgets to the dashboard',
				'type' 	=> 'section_title',
			),
			'dash_widget_custom_html_enabled' => array(
				'label' => 'Enable Custom HTML Widgets',
				'description' => 'Enable custom HTML dashboard widgets',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
				'autoload' => 'no',
			),
			// Widget 1
			'dash_widget_custom_html_label_1' => array(
				'label' => 'Widget 1 Title',
				'type' => 'text',
				'default' => 'Custom Widget',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'dash_widget_custom_html_cap_1' => array(
				'label' => 'Widget 1: Minimum Capability',
				'description' => 'Required capability (manage_options, edit_translations, edit_pages, create_posts)',
				'type' => 'text',
				'default' => 'delete_plugins',
				'sanitize_callback' => 'sanitize_text_field',
			),
			'dash_widget_custom_html_content_1' => array(
				'label' => 'Widget 1 Content',
				'description' => 'HTML content for widget 1 (shortcodes are processed)',
				'type' => 'html',
				'rows' => 4,
				'default' => '',
				'restricted' => true,
				'autoload' => 'no',
			),
			// Widget 2
			'dash_widget_custom_html_label_2' => array(
				'label' => 'Widget 2 Title',
				'type' => 'text',
				'default' => 'Custom Widget',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'dash_widget_custom_html_cap_2' => array(
				'label' => 'Widget 2: Minimum Capability',
				'description' => 'Required capability (manage_options, edit_translations, edit_pages, create_posts)',
				'type' => 'text',
				'default' => 'delete_plugins',
				'sanitize_callback' => 'sanitize_text_field',
			),
			'dash_widget_custom_html_content_2' => array(
				'label' => 'Widget 2 Content',
				'description' => 'HTML content for widget (shortcodes are processed)',
				'type' => 'html',
				'rows' => 4,
				'default' => '',
				'restricted' => true,
				'autoload' => 'no',
			),
			// Widget 3
			'dash_widget_custom_html_label_3' => array(
				'label' => 'Widget 3 Title',
				'type' => 'text',
				'default' => 'Custom Widget',
				'sanitize_callback' => 'sanitize_text_field',
				'autoload' => 'no',
			),
			'dash_widget_custom_html_cap_3' => array(
				'label' => 'Widget 3: Minimum Capability',
				'description' => 'Required capability (manage_options, edit_translations, edit_pages, create_posts)',
				'type' => 'text',
				'default' => 'delete_plugins',
				'sanitize_callback' => 'sanitize_text_field',
			),
			'dash_widget_custom_html_content_3' => array(
				'label' => 'Widget 3 Content',
				'description' => 'HTML content for widget (shortcodes are processed)',
				'type' => 'html',
				'rows' => 4,
				'default' => '',
				'restricted' => true,
				'autoload' => 'no',
			),
		),
	),
	'features' => array(
		'title' => 'Core Features',
		'fields' => array(
			'section_title_themekit_settings' => array(
				'label' => 'Themekit',
				'description' => 'Enable/disable Themekit features.',
				'type' => 'section_title',
			),
			'themekit_body_classes' => array(
				'label' => 'Add Body Classes',
				'description' => 'Add body classes to the frontend and admin body tag',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),			
			'themekit_base_css' => array(
				'label' => 'Add Plugin themekit-styles.css',
				'description' => 'Adds a supplemental <code>themekit-styles.css</code> stylesheet with base CSS styles that cannot be handled by theme.json.',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'themekit_font_display_swap' => array(
				'label' => 'Font Display Swap',
				'description' => 'Replace <code>font-display: fallback</code> with <code>font-display: swap</code> for WordPress Font Library fonts to improve Core Web Vitals',
				'type' => 'checkbox',
				'default' => 0,
				'sanitize_callback' => 'absint',
			),
			'themekit_remove_wp_patterns' => array(
				'label' => 'Remove WP Block Patterns',
				'description' => 'Remove WP Core Block Patterns and remote patterns from the official Pattern Directory on WordPress.org',
				'type' => 'checkbox',
				'default' => 1,
				'sanitize_callback' => 'absint',
			),
			'themekit_remove_provider_patterns' => array(
				'label' => 'Remove Provider Block Patterns',
				'description' => 'Disable block patterns of specific themes/plugins. Enter provider namespace (usually folder slug, e.g."ollie"). One provider per line.',
				'type' => 'textlist',
				'default' => '',
				'placeholder' => 'ollie',
				'sanitize_callback' => 'sanitize_textarea_field',
			),
			'themekit_remove_provider_styles' => array(
				'label' => 'Remove Provider Styles',
				'description' => 'Disable styles by exact handle or provider slug. Enter provider slug or exact style handle ("ollie" or "global-styles"). One provider per line. <b>WARNING</b>: Removing WP Global Style ("global-styles") can break current theme.',
				'type' => 'textlist',
				'default' => '',
				'placeholder' => 'greenshiftquery',
				'sanitize_callback' => 'sanitize_textarea_field',
			),
			'section_title_translator' => array(
				'type' => 'section_title',
				'label' => 'Translator',
				'description' => 'Dynamic translations for custom fields and metadata from any source.',
			),
			'translator_taxonomies' => array(
				'type' => 'checkbox',
				'label' => 'Translate Taxonomies',
				'description' => 'Translates taxonomy names and descriptions (defined in FRL_TRANSLATOR_TAXONOMIES).',
				'default' => '0',
			),
			'translator_posts' => array(
				'type' => 'checkbox',
				'label' => 'Translate Post Meta Fields',
				'description' => 'Translates custom fields on single posts, pages, and custom post types.',
				'default' => '0',
			),
			'translator_terms' => array(
				'type' => 'checkbox',
				'label' => 'Translate Taxonomy Fields',
				'description' => 'Translates custom fields on category, tag, and custom taxonomy archive pages.',
				'default' => '0',
			),
			'translator_users' => array(
				'type' => 'checkbox',
				'label' => 'Translate User Fields',
				'description' => 'Translates custom fields attached to user profiles.',
				'default' => '0',
			),
			'translator_options' => array(
				'type' => 'checkbox',
				'label' => 'Translate Site Options Fields',
				'description' => 'Translates fields saved in the options table (e.g., from an ACF Options Page).',
				'default' => '0',
			),
			'section_title_rewriter' => array(
				'label' => 'Rewriter',
				'description' => 'Custom rewriter features with priority-based URL processing',
				'type' => 'section_title',
			),
			'translate_post_base' => array(
				'label' => 'Post Base Translation',
				'description' => 'Add language-specific post base to URLs. Adapts to permalink structure: with %category% creates /en/news/tech/article-name, without creates /en/news/article-name. Format: lang|base per line. Priorities: 10 (Archives) & 20 (Singles).',
				'placeholder' => "en|news\nit|notizie",
				'type' => 'textlist',
				'default' => '',
				'sanitize_callback' => 'sanitize_textarea_field',
				'restricted' => true,
			),
			'translate_cpt_slugs' => array(
				'label' => 'CPT Base Translation',
				'description' => 'Translate CPT base in URLs for multilingual sites. Each CPT requires configuration in FRL_REWRITER_MULTILINGUAL_CPT constant. Format: lang|slug per line. Priorities: 15 (Archives) & 25 (Singles).',
				'placeholder' => "en|services\nit|servizi",
				'type' => 'custom',
				'callback' => 'frl_render_rewrite_multilingual_cpts',
				'restricted' => true,
			),
			'remove_tax_base' => array(
				'label' => 'Taxonomy Base Removal',
				'description' => 'Remove taxonomy base from categories and custom taxonomies (e.g., /tech/ instead of /category/tech/). One taxonomy per line. Priority 35.',
				'type' => 'textlist',
				'default' => 'category',
				'placeholder' => 'category',
				'sanitize_callback' => 'sanitize_textarea_field',
				'restricted' => true,
			),
			'remove_tax_base_info' => array(
				'label' => 'Registered Taxonomies',
				'type' => 'custom',
				'callback' => 'frl_render_rewrite_taxonomies',
			),
			'remove_cpt_base' => array(
				'label' => 'CPT Base Removal',
				'description' => 'Remove CPT base from URLs (e.g., /my-service/ instead of /service/my-service/). One CPT slug per line. Priority 40.',
				'type' => 'textlist',
				'default' => "flag\njurisdiction",
				'placeholder' => "flag\njurisdiction",
				'sanitize_callback' => 'sanitize_textarea_field',
				'restricted' => true,
			),
			'remove_cpt_base_info' => array(
				'label' => 'Registered CPTs',
				'type' => 'custom',
				'callback' => 'frl_render_rewrite_cpts',
			),
		),
	),
	'settings' => array(
		'title' => 'Plugin Settings',
		'fields' => array(
			'excluded_plugins_frontend_enabled' => array(
				'label' => 'Enable Frontend Exclusion',
				'description' => 'Block plugins on frontend (applies to all users).',
				'type' => 'checkbox',
				'default' => 0,
			),
			'excluded_plugins_frontend' => array(
				'label' => 'Frontend Excluded Plugins',
				'description' => 'One plugin path per line (e.g., hello Dolly/hello.php).',
				'type' => 'textlist',
				'default' => '',
			),
			'excluded_plugins_bycap_enabled' => array(
				'label' => 'Enable Admin Capability Exclusion',
				'description' => 'Block plugins in admin for users without capability.',
				'type' => 'checkbox',
				'default' => 0,
			),
			'excluded_plugins_bycap_cap' => array(
				'label' => 'Required Capability',
				'description' => 'Capability needed to load excluded plugins in admin.',
				'type' => 'text',
				'default' => 'delete_plugins',
			),
			'excluded_plugins_bycap' => array(
				'label' => 'Admin Excluded Plugins',
				'description' => 'One plugin path per line (e.g., hello Dolly/hello.php).',
				'type' => 'textlist',
				'default' => '',
			),
			'section_title_components' => array(
				'label' => 'Disable Core Features',
				'description' => 'Disable core plugin features',
				'type' => 'section_title',
			),
			'disable_cache' => array(
				'label' => 'Disable Cache Manager',
				'description' => 'Bypass plugin cache manager and retrieve options directly from the database.',
				'type' => 'checkbox',
				'default' => 0,
				'restricted' => true,
			),
			'disable_environment' => array(
				'label' => 'Disable Environment Manager',
				'description' => 'Bypass automatic runtime environment selection based on current host.',
				'type' => 'checkbox',
				'default' => 0,
				'restricted' => true,
			),
			'disable_translator' => array(
				'type' => 'checkbox',
				'label' => 'Disable Translator',
				'description' => 'Disable dynamic translation features for post, options, users, terms metadata. Note: the core translation service for shortcodes and blocks will still be active.',
				'default' => '0',
			),
			'disable_rewriter' => array(
				'type' => 'checkbox',
				'label' => 'Disable Rewriter',
				'description' => 'Disable rewriter features.',
				'default' => '0',
			),
			'disable_plugin' => array(
				'label' => 'Disable Plugin',
				'description' => 'Disable all plugin features (except admin, shortcodes, translations and theme.json).',
				'type' => 'checkbox',
				'default' => 0,
				'restricted' => true,
			),
		),
	),
	'developer' => array(
		'title' => 'Developer Tools',
		'fields' => array(
			'section_title_debug' => array(
				'label' => 'Debug mode',
				'description' => 'wp-config.php settings',
				'type' => 'section_title',
			),
			'debug' => array(
				'label' => 'WP_DEBUG',
				'description' => 'Enable WordPress debug mode',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'debug_log' => array(
				'label' => 'WP_DEBUG_LOG',
				'description' => 'Log errors to wp-content/debug.log',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'debug_display' => array(
				'label' => 'WP_DEBUG_DISPLAY',
				'description' => 'Display errors and warnings on screen',
				'type' => 'checkbox',
				'default' => 0,
				'restricted' => true,
			),
			'section_title_error_reporting' => array(
				'label' => 'Error reporting',
				'description' => 'Error reporting settings',
				'type' => 'section_title',
			),
			'error_reporting_email' => array(
				'label' => 'Email on Error',
				'description' => 'Send email notification on plugin error',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'error_reporting_notice' => array(
				'label' => 'Log Notices',
				'description' => 'Log notices in the debug.log file',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'error_reporting_warning' => array(
				'label' => 'Log Warnings',
				'description' => 'Log warnings in the debug.log file',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'error_reporting_deprecated' => array(
				'label' => 'Log Deprecated',
				'description' => 'Log deprecated messages in the debug.log file',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'error_reporting_plugin' => array(
				'label' => 'Log Plugin Only',
				'description' => 'Log only messages from this plugin in the debug.log file',
				'type' => 'checkbox',
				'default' => 1,
				'restricted' => true,
			),
			'error_reporting_suppressed' => array(
				'label' => 'Suppress error patterns',
				'description' => 'Suppress specific error types and patterns. One pattern per line. Format: string1(|string2|string3)',
				'type' => 'textlist',
				'default' => '_load_textdomain_just_in_time',
				'sanitize_callback' => 'sanitize_textarea_field',
				'restricted' => true,
			),
		),
	),
);
